django_site/django_site/urls.py
from django.contrib import admin
from django.urls import path, include
from zerShop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/signup/', views.SignUpView.as_view(), name='signup'),
    path('products/', include('zerShop.urls')),
    path('api/products/', views.ProductListAPI.as_view(), name='api_product_list'),
    path('api/products/update/', views.ProductUpdateAPI.as_view(), name='api_product_update'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_site/zerShop/urls.py
from django.urls import path, include
from zerShop import views

urlpatterns = [
    path('', views.ProductList.as_view(), name='products'),
    path('<int:pk>', views.ProductDetail.as_view(), name='product'),
    path('<int:pk>/edit/', views.ProductEdit.as_view(), name='product_edit'),
    path('<int:pk>/delete/', views.ProductDelete.as_view(), name='product_delete'),
    path('<int:pk>/order/', views.OrderFormView.as_view(), name='product_order'),
    path('<int:pk>/review/', views.AddReviewView.as_view(), name='add_review'),
    path('category/<int:pk>', views.CategoryDetail.as_view(), name='category'),
    path('categories/', views.CategoryList.as_view(), name='categories'),
    path('new/', views.ProductCreate.as_view(), name='product_new'),
    path('order_success/', views.OrderSuccessView.as_view(), name='order_success'),
]

django_site/zerShop/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime

# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=5000, null=True)
    category = models.ForeignKey('Category', on_delete='CASCADE', null=True, related_name='products')
    image = models.ImageField(upload_to='pics', null=True)
    price = models.IntegerField(default=0)
    price_discounted = models.IntegerField(null=True, blank=True)
    colors = (
        ('black', 'Черный'),
        ('gray', 'Серый'),
        ('yellow', 'Желтый'),
        ('green', 'Зеленый'),
        ('red', 'Красный'),
        ('blue', 'Синий'),
    )
    color = models.CharField(max_length=30, choices=colors, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product', args=[str(self.id)])

    def get_avg_rating(self):
        avg_rating = Review.rating
        return avg_rating

    
class Category(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=5000)

    def __str__(self):
        return self.title

class Order(models.Model):
    product = models.ForeignKey('Product', on_delete='CASCADE')
    customer_name = models.CharField(max_length=200)
    customer_phone = models.CharField(max_length=200)
    customer_email = models.EmailField(max_length=200)
    user = models.ForeignKey('auth.User', on_delete='CASCADE', null=True)

    def __str__(self):
        return self.customer_email

class Review(models.Model):
    user = models.ForeignKey('auth.User', on_delete='CASCADE')
    product = models.ForeignKey('Product', on_delete='CASCADE', related_name='products')
    content = models.TextField('Отзыв')
    pub_date = models.DateTimeField('Дата добавления отзыва', default=datetime.now)
    status = models.BooleanField('Показывать отзыв', default=False)
    stars = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),        
    )
    rating = models.IntegerField('Рейтинг товара', choices=stars, default='5')

    def __str__(self):
        return self.content[0:200]

    def get_absolute_url(self):
        return reverse('product', args=[self.product.id])

    def rating_range(self):
        return range(self.rating)

django_site/zerShop/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import generic
from rest_framework import generics, permissions
from rest_framework.renderers import (BrowsableAPIRenderer, JSONRenderer)

from .models import Category, Order, Product, Review
from .serializers import ProductSerializer

# Create your views here.

class ProductList(generic.ListView):
    template_name = 'products_list.html'
    context_object_name = 'products'
    model = Product
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

class ProductDetail(generic.DetailView):
    template_name = 'product_detail.html'
    context_object_name = 'product'
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['reviews'] = Review.objects.filter(product_id=self.kwargs['pk'])
        return context

class CategoryDetail(generic.DetailView):
    template_name = 'categoty_detail.html'
    context_object_name = 'category'
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

class CategoryList(generic.ListView):
    template_name = 'category_list.html'
    context_object_name = 'categories'
    model = Category

class ProductCreate(UserPassesTestMixin, generic.CreateView):
    model = Product
    template_name = 'product_new.html'
    fields = '__all__'
    login_url = '/'
    
    def test_func(self): 
          return self.request.user.is_superuser

class ProductEdit(UserPassesTestMixin, generic.UpdateView):
    model = Product
    template_name = 'product_new.html'
    fields = '__all__'
    login_url = '/'

    def test_func(self): 
          return self.request.user.is_superuser

class ProductDelete(UserPassesTestMixin, generic.DeleteView):
    model = Product
    template_name = 'product_delete.html'
    success_url = reverse_lazy('products')
    login_url = '/'

    def test_func(self): 
          return self.request.user.is_superuser

class OrderFormView(LoginRequiredMixin, generic.CreateView):
    model = Order
    template_name = 'product_order.html'
    success_url = reverse_lazy('order_success')
    fields = ['customer_name','customer_phone','customer_email']

    def form_valid(self, form):
        product = Product.objects.get(id=self.kwargs['pk'])
        user = self.request.user
        form.instance.user = user
        form.instance.product = product
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = Product.objects.get(id=self.kwargs['pk'])
        return context

class OrderSuccessView(generic.TemplateView):
    template_name = 'order_success.html'

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'
    context_object_name = 'sign'

class AddReviewView(LoginRequiredMixin, generic.CreateView):
    model = Review
    template_name = 'review_add.html'
    fields = ['content','rating']
    login_url = 'login'

    def form_valid(self, form):
        product_id = Product.objects.get(id=self.kwargs['pk'])
        user_id = self.request.user
        form.instance.user = user_id
        form.instance.product = product_id
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_id'] = Product.objects.get(id=self.kwargs['pk'])
        context['user_id'] = self.request.user
        return context

class ProductListAPI(generics.ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    renderer_classes = (JSONRenderer, BrowsableAPIRenderer, )

class ProductUpdateAPI(generics.UpdateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    renderer_classes = (BrowsableAPIRenderer, )
    permission_classes = (permissions.IsAdminUser, )

django_site/zerShop/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>zerShop</title>
    <meta name="keywords" content="Телефоны, Ноутбуки, Игровые консоли">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <link href="/media/css/bootstrap_style.css" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
</head>

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'products' %}">zerShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarsExampleDefault">
            <ul class="navbar-nav m-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'categories' %}">Categories
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Product</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Cart</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>

            <form class="form-inline my-2 my-lg-0">
                {% if user.is_authenticated %}
                <div class="btn-group">
                    {% if request.user.is_superuser %}
                    <button type="button" class="btn btn-success btn-sm ml-3 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{% url 'product_new' %}">Добавить продукт</a>
                        <a class="dropdown-item" href="/admin/">Админка</a>
                    </div>
                    {% else %}
                    <button type="button" class="btn btn-success btn-sm ml-3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </button>
                    {% endif %}
                </div>
                <a class="btn btn-success btn-sm ml-3" href="{% url 'logout' %}">Выйти</a>
                {% else %}
                <a class="btn btn-success btn-sm ml-3" href="{% url 'signup' %}">Регистрация</a>
                <a class="btn btn-success btn-sm ml-3" href="{% url 'login' %}">Войти</a>
                {% endif %}
            </form>
        </div>
    </div>
</nav>
{% block auth %} {% endblock %} {% block content %} {% endblock %}
<footer class="text-light">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-lg-4 col-xl-3">
                <h5>About</h5>
                <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                <p class="mb-0">
                    Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.
                </p>
            </div>

            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto">
                <h5>Informations</h5>
                <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                <ul class="list-unstyled">
                    <li>
                        <a href="">Link 1</a>
                    </li>
                    <li>
                        <a href="">Link 2</a>
                    </li>
                    <li>
                        <a href="">Link 3</a>
                    </li>
                    <li>
                        <a href="">Link 4</a>
                    </li>
                </ul>
            </div>

            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto">
                <h5>Others links</h5>
                <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                <ul class="list-unstyled">
                    <li>
                        <a href="">Link 1</a>
                    </li>
                    <li>
                        <a href="">Link 2</a>
                    </li>
                    <li>
                        <a href="">Link 3</a>
                    </li>
                    <li>
                        <a href="">Link 4</a>
                    </li>
                </ul>
            </div>

            <div class="col-md-4 col-lg-3 col-xl-3">
                <h5>Contact</h5>
                <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                <ul class="list-unstyled">
                    <li>
                        <i class="fa fa-home mr-2"></i> zerShop</li>
                    <li>
                        <i class="fa fa-envelope mr-2"></i> info@zershop.com</li>
                    <li>
                        <i class="fa fa-phone mr-2"></i> + 8 800 555 35 35</li>
                    <li>
                        <i class="fa fa-print mr-2"></i> + 8 800 555 55 55</li>
                </ul>
            </div>
            <div class="col-12 copyright mt-3">
                <p class="float-left">
                    <a href="#">Back to top</a>
                </p>
                <p class="text-right text-muted">created with
                    <i class="fa fa-heart"></i> by
                    <a href="https://t-php.fr/43-theme-ecommerce-bootstrap-4.html">
                        <i>t-php</i>
                    </a> |
                    <span>v. 1.0</span>
                </p>
            </div>
        </div>
    </div>
</footer>

django_site/zerShop/templates/category_list.html
{% extends 'base.html' %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'products' %}">Home</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-3">
            <div class="card bg-light mb-3">
                <div class="card-header bg-primary text-white text-uppercase">
                    <i class="fa fa-list"></i> Категории</div>
                <ul class="list-group category_block">
                    {% for category in categories %}
                    <li class="list-group-item">
                        <a href="{% url 'category' category.id %}">{{category.title}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

django_site/zerShop/templates/categoty_detail.html
{% extends 'base.html' %} {% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">{{ category.title }}</h1>
        <p class="lead text-muted mb-0">{{ category.description }}</p>
    </div>
</section>
<div class="container">
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'products' %}">Home</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">{{category.title}}</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-3">
            <div class="card bg-light mb-3">
                <div class="card-header bg-primary text-white text-uppercase">
                    <i class="fa fa-list"></i> Категории</div>
                <ul class="list-group category_block">
                    {% for category in categories %}
                    <li class="list-group-item">
                        <a href="{% url 'category' category.id %}">{{category.title}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="card bg-light mb-3">
                <div class="card-header bg-success text-white text-uppercase">Last product</div>
                <div class="card-body">
                    <img class="img-fluid" src="https://dummyimage.com/600x400/55595c/fff" />
                    <h5 class="card-title">Product title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <p class="bloc_left_price">99.00 $</p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                {% for product in category.products.all %}
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="card">
                        <img class="card-img-top" src="/media/{{product.image}}" alt="{{product.title}}">
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{% url 'product' product.id %}" title="View Product">{{product.title}}</a>
                            </h4>
                            <p class="card-text">{{product.description|truncatewords:25}}</p>
                            <div class="row">
                                <div class="col">
                                    <p class="btn btn-danger btn-block">{{product.price}} руб.</p>
                                </div>
                                <div class="col">
                                    <a href="{% url 'product_order' product.id %}" class="btn btn-success btn-block">Добавить в корзину</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %} {% if is_paginated %}
                <div class="col-12">
                    <nav aria-label="pages">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Назад</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <span class="page-link">Назад</span>
                            </li>
                            {% endif %} {% for i in paginator.page_range %} {% if page_obj.number == i %}
                            <li class="page-item active">
                                <span class="page-link" href="#">{{ i }}
                                    <span class="sr-only">(current)</span>
                                </span>
                            </li>
                            {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                            </li>
                            {% endif %} {% endfor %} {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Вперед</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <span class="page-link">Вперед</span>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
                {% endif %}
            </div>
        </div>

    </div>
</div>
{% endblock %}

django_site/zerShop/templates/order_success.html
{% extends 'base.html' %} {% block auth %}
<div class="row justify-content-center">
    <div class="col-4">
        <h1>Ваш заказ принят!</h1>
    </div>
</div>
{% endblock %}

django_site/zerShop/templates/product_delete.html
{% extends 'base.html' %} {% block auth %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-6">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>Вы действительно хотите удалить "{{ product.title }}"?</p>
                <input type="submit" value="Подтвердить" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

django_site/zerShop/templates/product_detail.html
{% extends 'base.html' %} {% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">{{ product.title }}</h1>
        <p class="lead text-muted mb-0">{{ product.description }}</p>
    </div>
</section>
<div class="container">
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'products' %}">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'category' product.category.id %}">{{product.category.title}}</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">{{product.title}}</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <!-- Image -->
        <div class="col-12 col-lg-6">
            {% if request.user.is_superuser %}
            <a class="btn btn-primary" href="{% url 'product_edit' product.pk %}">Править продукт</a>
            <a class="btn btn-primary" href="{% url 'product_delete' product.pk %}">Удалить продукт</a>
            {% endif %}
            <div class="card bg-light mb-3">
                <div class="card-body">
                    <a href="" data-toggle="modal" data-target="#productModal">
                        <img class="img-fluid" src="/media/{{product.image}}" />
                        <p class="text-center">Увеличить</p>
                    </a>
                </div>
            </div>
        </div>

        <!-- Add to cart -->
        <div class="col-12 col-lg-6 add_to_cart_block">
            <div class="card bg-light mb-3">
                <div class="card-body">
                    <p class="price">{{product.price}} руб.</p>
                    {% if product.price_discounted %}
                    <p class="price_discounted">{{product.price_discounted}} руб.</p>
                    {% endif %}
                    <form method="get" action="cart.html">
                        <div class="form-group">
                            <label for="colors">Цвет: </label>
                            <span> {{ product.get_color_display }}</span>
                        </div>
                        <div class="form-group">
                            <label>Количество :</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <button type="button" class="quantity-left-minus btn btn-danger btn-number" data-type="minus" data-field="">
                                        <i class="fa fa-minus"></i>
                                    </button>
                                </div>
                                <input type="text" class="form-control" id="quantity" name="quantity" min="1" max="100" value="1">
                                <div class="input-group-append">
                                    <button type="button" class="quantity-right-plus btn btn-success btn-number" data-type="plus" data-field="">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'product_order' product.id %}" class="btn btn-success btn-lg btn-block text-uppercase">
                            <i class="fa fa-shopping-cart"></i> Добавить в корзину
                        </a>
                    </form>
                    <div class="product_rassurance">
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <i class="fa fa-truck fa-2x"></i>
                                <br/>Fast delivery</li>
                            <li class="list-inline-item">
                                <i class="fa fa-credit-card fa-2x"></i>
                                <br/>Secure payment</li>
                            <li class="list-inline-item">
                                <i class="fa fa-phone fa-2x"></i>
                                <br/>+8 800 555 35 35</li>
                        </ul>
                    </div>
                    <div class="reviews_product p-3 mb-2 ">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        (4/5) {% if reviews %}
                        <a class="pull-right" href="#reviews">Смотреть все отзывы</a>
                        {% endif %}
                    </div>
                    <div class="datasheet p-3 mb-2 bg-info text-white">
                        <a href="" class="text-white">
                            <i class="fa fa-file-text"></i> Download DataSheet</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <!-- Description -->
        <div class="col-12">
            <div class="card border-light mb-3">
                <div class="card-header bg-primary text-white text-uppercase">
                    <i class="fa fa-align-justify"></i> Описание</div>
                <div class="card-body">
                    <p class="card-text">
                        {{product.description}}
                    </p>
                </div>
            </div>
        </div>

        <!-- Reviews -->
        <div class="col-12" id="reviews">
            <div class="card border-light mb-3">
                <div class="card-header bg-primary text-white text-uppercase">
                    <i class="fa fa-comment"></i> Отзывы</div>
                <div class="card-body">
                    {% for review in reviews %} {% if review.status %}
                    <div class="review">
                        <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                        <meta itemprop="datePublished" content="01-01-2016">{{ review.pub_date }} {% for x in review.rating_range %}
                        <span class="fa fa-star"></span>
                        {% endfor %} by {{ review.user }}
                        <p class="blockquote">
                            <p class="mb-0">{{ review.content }}</p>
                        </p>
                        <hr>
                    </div>
                    {% endif %} {% empty %}
                    <div class="review">
                        <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                        <p class="blockquote">
                            <p class="mb-0">Отзывов пока нет</p>
                        </p>
                        <hr>
                    </div>
                    {% endfor %}
                    <a class="btn btn-primary" href="{% url 'add_review' product.pk %}">Добавить отзыв</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal image -->
<div class="modal fade" id="productModal" tabindex="-1" role="dialog" aria-labelledby="productModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="productModalLabel">{{product.title}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <img class="img-fluid" src="/media/{{product.image}}" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<script>

    $(document).ready(function () {
        var quantity = 1;

        $('.quantity-right-plus').click(function (e) {
            e.preventDefault();
            var quantity = parseInt($('#quantity').val());
            $('#quantity').val(quantity + 1);
        });

        $('.quantity-left-minus').click(function (e) {
            e.preventDefault();
            var quantity = parseInt($('#quantity').val());
            if (quantity > 1) {
                $('#quantity').val(quantity - 1);
            }
        });

    });

</script> {% endblock %}

django_site/zerShop/templates/product_new.html
{% extends 'base.html' %} {% block auth %} {% load bootstrap %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %} {{ form|bootstrap }}
                <input type="submit" value="Подтвердить" />
            </form>
        </div>
    </div>
</div>
{% endblock %}